### ISSUE TITLE
Todo list.

### ISSUE THREAD

**Issue by kevyder** [kevyder/kevyder.github.io#1]
# Todo list.
- [ ] Header menu.
- [ ] About me section.
- [ ] Responsive design.
- [ ] Take a good picture.
- [ ] Improve projects filter.
- [ ] SEO.
- [ ] Domain.

**Comment by kevyder** [comment]
Scroll effect is done

**Comment by kevyder** [comment]
Fine!
